server:
  port:
    8088
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:cathay; # h2 database ????
    driver-class-name: org.h2.Driver # ??driver
    username: sa
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect